import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillInstagram,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-5 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Portfolio</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href = "https://drive.google.com/file/d/1BQgejd8nNcHeK0WXG1wL1Law05jusY6F/view?usp=share_link./Resume.pdf"
                  download
                  alt="resume"
                > 
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Prabhu Murthy
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-2xl">
              Developer and designer.
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-l">
              Hi, Im a college student creating my first portfolio using
              <span className="text-teal-500"> #tailwindcss</span>. These are my
              social media accounts, lets get connected.
            </p>
            <div className="text-2xl flex justify-center gap-8 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://twitter.com/PrabhuMurthy5">
                <AiFillTwitterCircle />
              </a>
              <a href="https://www.linkedin.com/in/prabhu-murthy-998403215/">
                <AiFillLinkedin />
              </a>
              <a href="https://www.instagram.com/prabhu___.3/">
                <AiFillInstagram />
              </a>
              <a href="https://github.com/PrabhuM143">
                <AiFillGithub />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-50 h-50 relative overflow-hidden mt-5 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" alt="dev" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-5 dark:text-white hover:text-teal-500 text-center hover:underline">
              Experience
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Im Still at college{" "}
              <span className="text-teal-500">
                (SRM Institute of Science and Technology : Kattankulathur)
              </span>
              , I didnt get enough experience. But, I have done a Intership of 6
              months in <br />
              <a
                className="text-teal-500 hover:text-teal-700"
                href="https://puriszerox.com/"
              >
                PurisZeroX_
              </a>
              a automobile ceramic coating company which has many branches all
              of India and around the globe, and
              <br />I have done some awesome projects.
            </p>
            <h3 className="text-3xl py-5 dark:text-white hover:text-teal-500 text-center hover:underline">
              Skills
            </h3>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} alt="alternative" />
              <h3 className="text-lg font-medium pt-8 pb-2  ">For Designing</h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Canva</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} alt="alternative" />
              <h3 className="text-lg font-medium pt-8 pb-2 ">For Coding</h3>
              <p className="py-2">
                Do you have an idea for your next great website? Lets make it a
                reality.
              </p>
              <h4 className="py-4 text-teal-600">Coding Tools I Use</h4>
              <p className="text-gray-800 py-1">VSCode</p>
              <p className="text-gray-800 py-1">Pycharm</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image
                src={consulting}
                width={100}
                height={100}
                alt="alternative"
              />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Extra</h3>
              <p className="py-2">
                Having an Extra weapon in arsenal is always better
              </p>
              <h4 className="py-4 text-teal-600">
                Tools I Use <br /> ( begginer )
              </h4>
              <p className="text-gray-800 py-1">Premiere Pro</p>
              <p className="text-gray-800 py-1">After Effect</p>
              <p className="text-gray-800 py-1">Unreal Engine</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-5 dark:text-white text-center hover:underline">
              Projects
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I have many mini-projects while practicing inmy courses
              completion, a fraction of that were added in my Github
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              The major project are as below:
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/4 flex-1 ">
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                This is the Project done in the Internship for Puris
              </p>
              <a href="https://puriszerox.com/">
                <Image
                  className="rounded-lg object-cover hover:blur-sm"
                  width={"100%"}
                  height={"60%"}
                  layout="responsive"
                  src={web1}
                  alt="project1"
                />
              </a>
            </div>
            <div className="basis-1/4 flex-1 ">
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                This is the Project done in college welfare
              </p>
              <a href="https://biodiversity.srmist.edu.in/">
                <Image
                  className="rounded-lg object-cover hover:blur-sm"
                  width={"100%"}
                  height={"60%"}
                  layout="responsive"
                  src={web2}
                  alt="project2"
                />
              </a>
            </div>
          </div>
          <div className="text-center text-xs py-0 dark:text-white">
            *For furthur contact, mail me on
            <span className="text-teal-500"> prabhumurthy143@gmail.com</span>
          </div>
        </section>
      </main>
    </div>
  );
}
